Moved common code of start scripts into new Tj3AppBase class.

diff --git a/test/TestSuite/StatusSheets/run b/test/TestSuite/StatusSheets/run
--- a/test/TestSuite/StatusSheets/run
+++ b/test/TestSuite/StatusSheets/run
@@ -8,32 +8,34 @@ function cleanup
   killall -9 tj3 2> /dev/null
 }
 
+function error
+{
+  echo "ERROR: $1"
+  exit 1
+}
+
 cleanup
 tj3 -s project.tjp &
 # Wait some time so tj3 can go into server mode.
 sleep 5 
 
 # Run a sender test.
-tj3ss_sender --dryrun -e 2002-03-02 > sender.log || exit 1
+tj3ss_sender --dryrun -e 2002-03-02 > sender.log || error "sender1"
 # Run a receiver test
-tj3ss_receiver --dryrun < boss_mail >> receiver.log || exit 1
-tj3ss_receiver --dryrun < dev2_mail >> receiver.log || exit 1
+tj3ss_receiver --dryrun < boss_mail >> receiver.log || error "rec1"
+tj3ss_receiver --dryrun < dev2_mail >> receiver.log || error "rec2"
 
 if test `fgrep ERROR statussheets.log | wc -l` != 0 ; then
-  echo "ERROR: Something went wrong!"
-  exit 1
+  error "Something went wrong!"
 fi  
 if test `fgrep WARN statussheets.log | wc -l` != 1 ; then
-  echo "ERROR: Warnings don't match!"
-  exit 1
+  error "ERROR: Warnings don't match!"
 fi  
 if test `fgrep INFO statussheets.log | wc -l` != 27 ; then
-  echo "ERROR: Info messages don't match!"
-  exit 1
+  error "ERROR: Info messages don't match!"
 fi  
 if test `fgrep 'Your weekly report template' statussheets.log | wc -l` != 2 ; then
-  echo "ERROR: Wrong number of emails send out!"
-  exit 1
+  error "ERROR: Wrong number of emails send out!"
 fi  
 
 cleanup
